### PR TITLE
Refactor testcases.

### LINKED ISSUE #22: Duplicated pylsy.py
https://github.com/Leviathan1995/Pylsy/blob/master/pylsy/tests/pylsy.py

### PR DESCRIPTION
**Pull request by bcho**
Remove dupliated pylsy.py. Tests can be ran with:

```
python setup.py test
```

Close #22.

### CODE REVIEW

**Comment by leviathan0992** [comment]
thank you very much!!!

**Comment by leviathan0992** [comment]
i can't understand "python setup.py test " in runtests.sh

**Comment by bcho** [comment]
You can use this tutor as reference:
http://www.scotttorborg.com/python-packaging/testing.html :)

2015-09-05 13:00 GMT+08:00 Leviathan notifications@github.com:

**Comment by leviathan0992** [comment]
thank you very much!

**Pull request merged**
