### PR TITLE
chinese supported

### PR DESCRIPTION
**Pull request by MrLYC**

### CODE REVIEW

**Comment by Artoria2e5** [comment]
This patch also adds Klingon support (ConScript Unicode Registry, in PUA), which is crucial for future communication with major alien empires.

Not accepting this patch and keep using `str(value)` in Py 2.7 (which often messes up with Unicode) will keep the Federation from being able to decode Klingon and finally lead to the end of humanity…

**Comment by Artoria2e5** [comment]
But in the meantime, you might also want to look into things like [wcwidth](https://github.com/jquast/wcwidth) for correct width calculation… Misaligned tables ruins Homo Sapiens' galactic image.

**Comment by Artoria2e5** [comment]
Let me try writing one.. warning: I don't usually code in python.

**Comment by leviathan0992** [comment]
宽度是可以计算的，但是对齐很麻烦，

**Comment by Artoria2e5** [comment]
With proper width calculation, alignment should be as easy as aligning ASCII text.

**Pull request closed without merging**
